services:
  api:
    build: .
    environment:
      - DATABASE_URL_DOTNET=${DATABASE_URL_DOTNET}
      - Auth0_Domain=${AUTH0_DOMAIN}
      - Auth0_Management_Audience=${AUTH0_MANAGMENT_AUDIENCE}
      - Auth0_JWT_Audience=${AUTH0_JWT_AUDIENCE}
      - Auth0_ClientId=${AUTH0_CLIENT_ID}
      - Auth0_ClientSecret=${AUTH0_CLIENT_SECRET}
    ports:
      - "7071:8080"

    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: admin
      POSTGRES_DB: Cibrary
    ports:
      - "5432:5432"
    volumes:
      - ./databases/postgres_data:/var/lib/postgresql/data
      - ./sql_scripts/createDatabase.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: unless-stopped
