version: "3.8"
services:
  api:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: admin
      POSTGRES_DB: Cibrary
    ports:
      - "5432:5432"
    volumes:
      - ./databases/postgres_data:/var/lib/postgresql/data
      - ./sql_scripts/createDatabase.sql:/docker-entrypoint-initdb.d/create_tables.sql
